server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Extract the container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Keep only farmer_ containers
      - source_labels: ['container']
        regex: 'farmer_(.*)'
        action: keep
      # Label the service based on the container name
      - source_labels: ['container']
        regex: 'farmer_(backend|frontend|ml_service)'
        target_label: 'service'
      # Extract the image
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
